# Generated by Django 4.1.3 on 2023-01-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="community",
            old_name="id_community",
            new_name="id",
        ),
    ]
